// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJp0CgtLUk7_Jk7tDcRkzuZ7Mmt9qBQvI',
    appId: '1:237246174464:web:66ca26551b62bd2ce24fe5',
    messagingSenderId: '237246174464',
    projectId: 'noubank-aa20e',
    authDomain: 'noubank-aa20e.firebaseapp.com',
    storageBucket: 'noubank-aa20e.firebasestorage.app',
    measurementId: 'G-WVLRDT5303',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI_4t3lrLxQsEAWW9snfUW2UJiGeerS34',
    appId: '1:237246174464:android:7e0c495198f98895e24fe5',
    messagingSenderId: '237246174464',
    projectId: 'noubank-aa20e',
    storageBucket: 'noubank-aa20e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdQSDPfrFb41XKEk_84-xoeQdyhbV3h1Y',
    appId: '1:237246174464:ios:5358ac739b71c70fe24fe5',
    messagingSenderId: '237246174464',
    projectId: 'noubank-aa20e',
    storageBucket: 'noubank-aa20e.firebasestorage.app',
    iosBundleId: 'com.example.noubank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdQSDPfrFb41XKEk_84-xoeQdyhbV3h1Y',
    appId: '1:237246174464:ios:5358ac739b71c70fe24fe5',
    messagingSenderId: '237246174464',
    projectId: 'noubank-aa20e',
    storageBucket: 'noubank-aa20e.firebasestorage.app',
    iosBundleId: 'com.example.noubank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJp0CgtLUk7_Jk7tDcRkzuZ7Mmt9qBQvI',
    appId: '1:237246174464:web:f2695e270e504d69e24fe5',
    messagingSenderId: '237246174464',
    projectId: 'noubank-aa20e',
    authDomain: 'noubank-aa20e.firebaseapp.com',
    storageBucket: 'noubank-aa20e.firebasestorage.app',
    measurementId: 'G-99J8Z23TKL',
  );
}
